# Generated by Django 5.1.6 on 2025-05-03 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='carts',
        ),
    ]
