# Generated by Django 5.1.6 on 2025-05-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cart_transaction'),
        ('transaction', '0002_remove_transaction_carts'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='carts',
            field=models.ManyToManyField(related_name='transactions', to='cart.cart'),
        ),
    ]
