# Generated by Django 5.1.6 on 2025-05-03 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('transaction', '0002_remove_transaction_carts'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='transaction.transaction'),
        ),
    ]
