# Generated by Django 5.1.6 on 2025-05-03 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='transaction',
        ),
    ]
