# Generated by Django 5.1.6 on 2025-05-24 10:09

import django.db.models.deletion
import equipment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.ForeignKey(default=equipment.models.Category.get_default_category, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='equipments', to='equipment.category'),
        ),
    ]
